version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - grafana_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana_network

volumes:
  postgres_data:
  grafana_data:

networks:
  grafana_network:
  